### ISSUE TITLE
Link to godocs + example

### ISSUE THREAD

**Issue by csmith** [greboid/irc#50]
It'd be nice if the README linked to the [docs for the latest version](https://pkg.go.dev/github.com/greboid/irc/v4) and it'd be super nice if the docs included a simple [example](https://blog.golang.org/examples) (connect, join a channel, send a message)?

**Comment by greboid** [comment]
I've decided to stop development on this, if you still need an irc library the ergo events library is much more complete than this, documented and easy to use
